[workspace]
channels = [
    "https://conda.rosettacommons.org",
    "https://conda.graylab.jhu.edu",
    "conda-forge",
]
name = "pyrosettacluster"
version = "0.1.0"

[dependencies]
python = ">=3.9"
pyrosetta = "*"

[pypi-dependencies]
pyrosetta-distributed = "*"
