name: pyrosettacluster
channels:
  - https://conda.rosettacommons.org
  - https://conda.graylab.jhu.edu
  - conda-forge
dependencies:
  - python>=3.9
  - pyrosetta
  - pip
  - pip:
    - pyrosetta-distributed
